import type { ScenarioTemplate } from '@/data/types';

// 6 Ready-to-Run Scenario Templates
export const scenarioTemplates: ScenarioTemplate[] = [
  {
    id: 'oee-analysis',
    name: 'OEE Drop Analysis',
    description: 'Why did Line-B OEE drop this shift?',
    category: 'analysis',
    icon: 'TrendingDown',
    estimatedDuration: 3,
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Gather Context',
        description: 'Select the line and shift to analyze',
        type: 'form',
        inputs: [
          {
            key: 'lineId',
            label: 'Production Line',
            type: 'select',
            required: true,
            options: [
              { label: 'Line-A', value: 'line-a' },
              { label: 'Line-B', value: 'line-b' },
              { label: 'Line-C', value: 'line-c' },
            ],
          },
          {
            key: 'shift',
            label: 'Shift',
            type: 'select',
            required: true,
            options: [
              { label: 'Morning (06:00-14:00)', value: 'morning' },
              { label: 'Afternoon (14:00-22:00)', value: 'afternoon' },
              { label: 'Night (22:00-06:00)', value: 'night' },
            ],
          },
        ],
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Analyze OEE Components',
        description: 'Data Agent calculates availability, performance, and quality',
        type: 'agent',
        agentId: 'data-agent',
        prompt: 'Calculate OEE breakdown for {lineId} during {shift} shift. Compare to baseline and identify which component (availability, performance, or quality) contributed most to the drop.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Identify Root Causes',
        description: 'Orchestrator routes to appropriate specialist agent',
        type: 'agent',
        agentId: 'orchestrator',
        prompt: 'Based on the OEE analysis, identify the top 3 root causes for the drop. Include downtime events, quality issues, and performance degradation.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Review Findings',
        description: 'Review analysis results and recommendations',
        type: 'review',
      },
    ],
  },
  {
    id: 'downtime-causes',
    name: 'Downtime Root Cause',
    description: 'Top 3 downtime causes today + fixes',
    category: 'downtime',
    icon: 'AlertTriangle',
    estimatedDuration: 4,
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Select Timeframe',
        description: 'Define the analysis period',
        type: 'form',
        inputs: [
          {
            key: 'date',
            label: 'Date',
            type: 'date',
            required: true,
          },
          {
            key: 'scope',
            label: 'Scope',
            type: 'select',
            required: true,
            options: [
              { label: 'All Lines', value: 'all' },
              { label: 'Single Line', value: 'single' },
            ],
          },
        ],
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Retrieve Downtime Events',
        description: 'Data Agent queries downtime logs',
        type: 'agent',
        agentId: 'data-agent',
        prompt: 'Retrieve all downtime events for {scope} on {date}. Group by reason code and calculate total duration for each.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Analyze Root Causes',
        description: 'Maintenance Agent identifies recurring patterns',
        type: 'agent',
        agentId: 'maintenance-agent',
        prompt: 'Analyze the downtime events and identify the top 3 root causes. For each cause, provide: total duration, frequency, affected equipment, and recommended corrective actions.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Generate Action Plan',
        description: 'Create actionable maintenance tasks',
        type: 'agent',
        agentId: 'maintenance-agent',
        prompt: 'For each of the top 3 root causes, generate specific maintenance tasks with priority, estimated time, and required parts.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Review Action Plan',
        description: 'Review findings and approve tasks',
        type: 'review',
      },
    ],
  },
  {
    id: 'quality-spotcheck',
    name: 'Quality Spot Check',
    description: 'Start visual quality spot-check for SKU X',
    category: 'quality',
    icon: 'CheckCircle',
    estimatedDuration: 5,
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Select Product',
        description: 'Choose the SKU to inspect',
        type: 'form',
        inputs: [
          {
            key: 'sku',
            label: 'Product SKU',
            type: 'select',
            required: true,
            options: [
              { label: 'SKU-001 (Coffee Maker)', value: 'sku-001' },
              { label: 'SKU-002 (Blender)', value: 'sku-002' },
              { label: 'SKU-003 (Toaster)', value: 'sku-003' },
            ],
          },
          {
            key: 'sampleSize',
            label: 'Sample Size',
            type: 'number',
            required: true,
          },
        ],
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Load Checklist',
        description: 'Quality Agent retrieves inspection checklist',
        type: 'agent',
        agentId: 'quality-agent',
        prompt: 'Retrieve the visual inspection checklist for {sku}. Include all critical dimensions, cosmetic checks, and functional tests.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Perform Inspection',
        description: 'Complete the inspection checklist',
        type: 'form',
        inputs: [
          {
            key: 'results',
            label: 'Inspection Results',
            type: 'multiselect',
            required: true,
            options: [
              { label: 'All checks passed', value: 'pass' },
              { label: 'Cosmetic defect', value: 'cosmetic' },
              { label: 'Dimensional issue', value: 'dimensional' },
              { label: 'Functional failure', value: 'functional' },
            ],
          },
          {
            key: 'notes',
            label: 'Additional Notes',
            type: 'text',
            required: false,
          },
        ],
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Analyze Results',
        description: 'Quality Agent evaluates defect patterns',
        type: 'agent',
        agentId: 'quality-agent',
        prompt: 'Analyze the inspection results for {sku}. If defects were found, identify potential root causes and recommend corrective actions.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Review & Submit',
        description: 'Finalize inspection report',
        type: 'review',
      },
    ],
  },
  {
    id: 'pm-task-creation',
    name: 'Create PM Task',
    description: 'Create PM task for Machine M after 1200 cycles',
    category: 'maintenance',
    icon: 'Wrench',
    estimatedDuration: 2,
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Machine Selection',
        description: 'Select the machine and trigger condition',
        type: 'form',
        inputs: [
          {
            key: 'machineId',
            label: 'Machine',
            type: 'select',
            required: true,
            options: [
              { label: 'Filler-1', value: 'filler-1' },
              { label: 'Filler-2', value: 'filler-2' },
              { label: 'Filler-3', value: 'filler-3' },
              { label: 'Sealer-1', value: 'sealer-1' },
            ],
          },
          {
            key: 'triggerCycles',
            label: 'Trigger After (cycles)',
            type: 'number',
            required: true,
          },
        ],
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Generate PM Checklist',
        description: 'Maintenance Agent creates task list',
        type: 'agent',
        agentId: 'maintenance-agent',
        prompt: 'Create a preventive maintenance checklist for {machineId} at {triggerCycles} cycles. Include inspection points, lubrication tasks, and parts to check.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Review & Schedule',
        description: 'Confirm task and assign technician',
        type: 'review',
      },
    ],
  },
  {
    id: 'shift-handover',
    name: 'Shift Handover Summary',
    description: 'Summarize shift handover for Line-A',
    category: 'analysis',
    icon: 'Users',
    estimatedDuration: 2,
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Select Context',
        description: 'Choose line and shift to summarize',
        type: 'form',
        inputs: [
          {
            key: 'lineId',
            label: 'Production Line',
            type: 'select',
            required: true,
            options: [
              { label: 'Line-A', value: 'line-a' },
              { label: 'Line-B', value: 'line-b' },
              { label: 'Line-C', value: 'line-c' },
            ],
          },
          {
            key: 'shift',
            label: 'Shift',
            type: 'select',
            required: true,
            options: [
              { label: 'Morning', value: 'morning' },
              { label: 'Afternoon', value: 'afternoon' },
              { label: 'Night', value: 'night' },
            ],
          },
        ],
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Retrieve Handover Notes',
        description: 'Handover Agent fetches voice transcripts',
        type: 'agent',
        agentId: 'handover-agent',
        prompt: 'Retrieve all handover notes for {lineId} during {shift} shift. Include voice transcripts and manual notes.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Generate Summary',
        description: 'Orchestrator creates concise summary',
        type: 'agent',
        agentId: 'orchestrator',
        prompt: 'Summarize the shift handover notes for {lineId}. Include: key events, production metrics, quality issues, maintenance performed, and open action items.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Review Summary',
        description: 'Review and share with incoming shift',
        type: 'review',
      },
    ],
  },
  {
    id: 'temperature-trend',
    name: 'Temperature Trend Analysis',
    description: 'Temperature trend on Filler-3',
    category: 'analysis',
    icon: 'Activity',
    estimatedDuration: 2,
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Select Parameters',
        description: 'Choose machine and time range',
        type: 'form',
        inputs: [
          {
            key: 'machineId',
            label: 'Machine',
            type: 'select',
            required: true,
            options: [
              { label: 'Filler-1', value: 'filler-1' },
              { label: 'Filler-2', value: 'filler-2' },
              { label: 'Filler-3', value: 'filler-3' },
            ],
          },
          {
            key: 'timeRange',
            label: 'Time Range',
            type: 'select',
            required: true,
            options: [
              { label: 'Last Hour', value: '1h' },
              { label: 'Last 4 Hours', value: '4h' },
              { label: 'Last Shift', value: 'shift' },
              { label: 'Last 24 Hours', value: '24h' },
            ],
          },
        ],
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Retrieve Temperature Data',
        description: 'Data Agent queries sensor history',
        type: 'agent',
        agentId: 'data-agent',
        prompt: 'Retrieve temperature sensor data for {machineId} over {timeRange}. Include min, max, average, and standard deviation.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Analyze Trend',
        description: 'Orchestrator identifies anomalies',
        type: 'agent',
        agentId: 'orchestrator',
        prompt: 'Analyze the temperature trend for {machineId}. Identify any spikes, drops, or drift from normal operating range. If anomalies detected, route to Maintenance Agent for diagnosis.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Review Analysis',
        description: 'View trend chart and recommendations',
        type: 'review',
      },
    ],
  },
];
